export declare const THUMB_WIDTH = 16;
export declare const container: string;
export declare const header: string;
export declare const label: string;
export declare const amount: string;
export declare const sliderWrapper: string;
export declare const sliderBackground: string;
export declare const sliderFill: string;
export declare const thumb: string;
export declare const rangeInput: string;
