export declare const BALANCE_AREAS = "balance-area";
export declare const CONTROLS_AREAS = "controls-area";
export declare const HEADER_AREAS = "header-area";
export declare const SYSTEM_AREAS = "system-area";
export declare const SCENE_AREAS = "scene-area";
export declare const INFO_AREAS = "info-area";
export declare const TICKET_AREAS = "ticket-area";
export declare const HIDDEN_AREAS = "hidden-area";
export declare const HISTORY_AREAS = "history-area";
export declare const slideLeft: string;
export declare const slideRight: string;
export declare const slideUp: string;
export declare const slideDown: string;
export declare const baseLayout: string;
export declare const mediaLayout: string;
export declare const drawer: string;
export declare const drawerLandscapeEnter: string;
export declare const drawerLandscapeExit: string;
export declare const drawerPortraitEnter: string;
export declare const drawerPortraitExit: string;
